[package]
name = "creare/roblox-visual-scripting-language"
description = "Visual scripting language"
license = "MIT"
authors = ["creare"]
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
signal = "sleitnick/signal@2.0.3"
